document:
  debug:
    enabled: true
    parameters:
      highlight_links: true
      highlight_frames: true

  document_class:
    name: article
    options: 9pt

  layout:
    dimensions:
      width: 138.00mm
      height: 188mm

    margin:
      top: 10mm
      bottom: 5mm
      left: 14mm
      right: 5mm

    margin_notes:
      width: 10mm
      separation: 6.3mm
      placement: left

parameters:
  template_name: mos
  compile:
    runs: 2
  parameters:
    header:
      vertical_padding_factor: 3
      column_spacing: 1.5pt
    start_date: 2023, January
    end_date: 2023, December
    weekday_start: Monday
    show_week_numbers: true
    format_ampm: false
    week_number_placement: left
    notes:
      type: dotted

sections:
  title:
    enabled: true
    parameters:
      name: 2023

  annual:
    enabled: true
    parameters:
        pages: 2
        months_per_page: 8
        columns: 2
        column_width: 5.6cm
        column_spacing: 1cm
        vertical_spacing: 1cm
        underfull_vertical_spacing: 1cm
