document:
  debug:
    enabled: true
    options:
      highlight_links: true
      highlight_frames: true

  layout:
    dimensions:
      width: 138.00mm
      height: 188mm

    margin:
      top: 10mm
      bottom: 5mm
      left: 14mm
      right: 5mm

    margin_notes:
      width: 10mm
      separator: 6.3mm
      placement: left


parameters:
  start_date: 2023, January
  end_date: 2023, December
  weekday_start: Monday
  show_week_numbers: true
  format_ampm: false
  week_number_placement: right


sections:
  title:
    name: 2023

  yearly:
    enabled: true

    pages: 2
    months_per_page: 8
    columns: 2
    column_width: 5cm
    column_spacing: 1cm
    vertical_spacing: 1cm


  quarterly:
    enabled: true

    calendars_column_width: 5cm
    calendars_column_height: 15cm
    calendars_column: right
    calendars_vertical_spacing: 1cm

  monthly:
    enabled: true

  weekly:
    enabled: true

  daily:
    enabled: true

  daily_reflections:
    enabled: true

  daily_notes:
    enabled: true

  notes:
    enabled: true

  tasks:
    enabled: true
